---
name: "CI"
on: [push]

jobs:
  build-all-platforms:
    runs-on: macos-11.0
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer

    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      # Gloop Drop

      - name: Check out Gloop Drop
        uses: actions/checkout@v2.3.4

      - name: Build Gloop Drop iOS
        working-directory: gloop-drop
        run: xcodebuild clean build -scheme iOS CODE_SIGNING_ALLOWED=NO

      - name: Build Gloop Drop macOS
        working-directory: gloop-drop
        run: xcodebuild clean build -scheme macOS CODE_SIGNING_ALLOWED=NO

      - name: Build Gloop Drop tvOS
        working-directory: gloop-drop
        run: xcodebuild clean build -scheme tvOS CODE_SIGNING_ALLOWED=NO

      # Val's Revenge

      - name: Check out Val's Revenge
        uses: actions/checkout@v2.3.4

      - name: Build Val's Revenge iOS
        working-directory: val-revenge
        run: xcodebuild clean build -scheme iOS CODE_SIGNING_ALLOWED=NO

      - name: Build Val's Revenge macOS
        working-directory: val-revenge
        run: xcodebuild clean build -scheme macOS CODE_SIGNING_ALLOWED=NO

      - name: Build Val's Revenge tvOS
        working-directory: val-revenge
        run: xcodebuild clean build -scheme tvOS CODE_SIGNING_ALLOWED=NO
